app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, url_for, redirect
from flask_login import current_user, login_required

from . import main


@main.route('/')
def index():
    return redirect(url_for('auth.login'))


@main.route('/dashboard')
@login_required
def dashboard():
    if current_user.role == 'dev':
        return redirect(url_for('dev.dev_chart', days=7))
    else:
        return render_template('main/dashboard.html')

app/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Inception | MySQL</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ url_for('static',filename='vendor/bootstrap/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ url_for('static',filename='vendor/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ url_for('static',filename='vendor/Ionicons/css/ionicons.min.css') }}">
    <!-- DataTables -->
    <link rel="stylesheet"
          href="{{ url_for('static',filename='vendor/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ url_for('static',filename='vendor/select2/css/select2.min.css') }}">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{ url_for('static',filename='vendor/iCheck/all.css') }}">
    <!-- SweetAlert2-->
    <link rel="stylesheet" href="{{ url_for('static',filename='vendor/sweetalert2/sweetalert2.min.css') }}">
    <!-- bootstrap datetimepicker -->
    <link rel="stylesheet" href="{{ url_for('static',filename='vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ url_for('static',filename='dist/css/AdminLTE.min.css') }}">
    <!-- Pace style -->
    <link rel="stylesheet" href="{{ url_for('static',filename='vendor/pace/pace.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ url_for('static',filename='dist/css/skins/skin-blue.min.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="#" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>I</b>CE</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Inception</b>MySQL</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Notifications: style can be found in dropdown.less -->
                    <!-- Control Sidebar Toggle Button -->
                    <li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.logout') }}">
                            <i class="fa fa-sign-out"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>


    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- search form (Optional) -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
                </div>
            </form>
            <!-- /.search form -->

            <!-- Sidebar Menu -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MAIN NAVIGATION</li>
                <!-- Optionally, you can add icons to the links -->
                {% if current_user.role == 'admin' %}
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-database"></i>
                            <span>DBs</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{{ url_for('admin.dbs') }}"><i class="fa fa-circle-o"></i>View</a></li>
                            <li><a href="{{ url_for('admin.db_create') }}"><i class="fa fa-circle-o"></i> Add</a></li>
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-users"></i>
                            <span>Users</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{{ url_for('admin.user') }}"><i class="fa fa-circle-o"></i>View</a></li>
                            <li><a href="{{ url_for('admin.user_create') }}"><i class="fa fa-circle-o"></i> Add</a></li>
                        </ul>
                    </li>
                {% endif %}

                {% if current_user.role == 'dev' %}
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-database"></i>
                            <span>DBs</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{{ url_for('dev.dev_resource') }}"><i class="fa fa-circle-o"></i>View</a></li>
                            <li><a href="{{ url_for('dev.dev_resource_request') }}"><i class="fa fa-circle-o"></i> Add</a></li>
                            <li><a href="{{ url_for('dev.dev_resource_status') }}"><i class="fa fa-circle-o"></i> Status</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-tasks"></i>
                            <span>Work Sheet</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{{ url_for('dev.dev_work') }}"><i class="fa fa-circle-o"></i>View</a></li>
                            <li><a href="{{ url_for('dev.dev_work_create') }}"><i class="fa fa-circle-o"></i> Create</a></li>
                        </ul>
                    </li>
                {% endif %}

                {% if current_user.role == 'audit' %}
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-database"></i>
                            <span>DBs</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{{ url_for('audit.audit_resource_pending') }}"><i class="fa fa-circle-o"></i> Pending</a></li>
                            <li><a href="{{ url_for('audit.audit_resource_dealt') }}"><i class="fa fa-circle-o"></i> Dealt</a></li>
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-tasks"></i>
                            <span>Work Sheet</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="{{ url_for('audit.audit_work_pending') }}"><i class="fa fa-circle-o"></i> Pending</a></li>
                            <li><a href="{{ url_for('audit.audit_work_dealt') }}"><i class="fa fa-circle-o"></i> Dealt</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="{{ url_for('audit.audit_work_timer_view') }}">
                            <i class="fa fa-calendar"></i>
                            <span>Timer</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
            <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% block content %}
        {% endblock %}
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
            <b>Version</b> 1.0.0
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2018 <a href="#">Company</a>.</strong> All rights reserved.
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
            <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <!-- Home tab content -->
            <div class="tab-pane active" id="control-sidebar-home-tab">

            </div>
            <!-- /.tab-pane -->
            <!-- Stats tab content -->
            <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
            <!-- /.tab-pane -->
            <!-- Settings tab content -->
            <div class="tab-pane" id="control-sidebar-settings-tab">
                <form method="post">
                    <div class="form-group">
                        <a href="" class="control-sidebar-subheading"></a>
                    </div>
                    <!-- /.form-group -->
                </form>
            </div>
            <!-- /.tab-pane -->
        </div>
    </aside>
    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
    immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="{{ url_for('static',filename='vendor/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ url_for('static',filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ url_for('static',filename='vendor/fastclick/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static',filename='dist/js/adminlte.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ url_for('static',filename='vendor/jquery-sparkline/jquery.sparkline.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ url_for('static',filename='vendor/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ url_for('static',filename='vendor/chart.js/Chart.js') }}"></script>
<!-- Pace style -->
<script src="{{ url_for('static',filename='vendor/pace/pace.min.js') }}"></script>

{% block js %}
{% endblock %}

{% block custom %}
{% endblock %}

{% block ajax %}
{% endblock %}
</body>
</html>

app/templates/main/dashboard.html
{% extends 'main/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

        <!--------------------------
          | Your Page Content Here |
          -------------------------->

    </section>
    <!-- /.content -->

{% endblock %}