app/audit/__init__.py
from flask import Blueprint

audit = Blueprint('audit', __name__)

from . import views

app/audit/views.py
from datetime import datetime
from datetime import timedelta
import json
import os

from flask import render_template, url_for, redirect, request, jsonify, flash, make_response, send_file, current_app
from flask_login import login_required, current_user

from .. import db, celery
from .. import audit_permission
from ..models import Dbapply, User, Dbconfig, Work
from ..inception import sql_auto_review, get_osc, stop_osc, get_sql_roll
from ..tasks import execute_task, send_mail
from . import audit

# Dictionary cache used for store SQL and corresponding SHA1
# Format: {work_flow_id1:{SQL_id1:sqlSHA1 value1, SQL_id2:sqlSHA1 value2}}
sql_sha1_cache = {}


@audit.route('/audit/resource/dealt')
@login_required
@audit_permission.require(http_exception=403)
def audit_resource_dealt():
    """
    Application from dev for db instances have been dealt.
    :return:
    """
    resources = Dbapply.query.filter(Dbapply.audit_name == current_user.name, Dbapply.status != 1)

    return render_template('audit/resource_dealt.html', resources=resources)


@audit.route('/audit/resource/pending')
@login_required
@audit_permission.require(http_exception=403)
def audit_resource_pending():
    """
    Application from dev for db instances will to be handled.
    :return:
    """
    resources = Dbapply.query.filter(Dbapply.audit_name == current_user.name, Dbapply.status == 1)

    return render_template('audit/resource_pending.html', resources=resources)


@audit.route('/audit/resource/alloc/<int:id>', methods=['POST', 'GET'])
@login_required
@audit_permission.require(http_exception=403)
def audit_resource_alloc(id):
    """
    Alloc db instances to dev.
    :param id:
    :return:
    """
    resource = Dbapply.query.get(id)
    user = User.query.filter(User.name == resource.dev_name).first()
    db_config = Dbconfig.query.filter(Dbconfig.name == resource.db_name).first()
    user.dbs.append(db_config)
    resource.finish_time = datetime.now()
    resource.status = 0

    db.session.add(resource)
    db.session.commit()

    if current_app.config['MAIL_ON_OFF'] == 'ON':
        dev = User.query.filter(User.name == resource.dev_name).first()
        mail_content = "<p>Proposer：" + resource.dev_name + "</p>" + "<p>Db instance's name：" + resource.db_name + \
                       "</p>" + "<p>Your db instance request has been passed.</p>"
        send_mail.delay('【inception_mysql】Db instance request passed', mail_content, dev.email)

    return redirect(url_for('.audit_resource_pending'))


@audit.route('/audit/resource/cancel/<int:id>')
@login_required
@audit_permission.require(http_exception=403)
def audit_resource_cancel(id):
    """
    Cancelled the application from dev.
    :param id:
    :return:
    """
    resource = Dbapply.query.get(id)
    resource.status = 3
    resource.finish_time = datetime.now()

    db.session.add(resource)
    db.session.commit()

    if current_app.config['MAIL_ON_OFF'] == 'ON':
        dev = User.query.filter(User.name == resource.dev_name).first()
        mail_content = "<p>Proposer：" + resource.dev_name + "</p>" + "<p>Db instance's name：" + resource.db_name + \
                       "</p>" + "<p>Your db instance request is disagreed.</p>"
        send_mail.delay('【inception_mysql】Db instance request failure', mail_content, dev.email)

    return redirect(url_for('.audit_resource_dealt'))


@audit.route('/audit/work/pending')
@login_required
@audit_permission.require(http_exception=403)
def audit_work_pending():
    """
    Work orders to be handled, exclude timer.
    :return:
    """
    works = Work.query.filter(Work.audit_name == current_user.name, Work.status == 1, Work.timer == None)

    return render_template('audit/work_pending.html', works=works)


@audit.route('/audit/work/dealt')
@login_required
@audit_permission.require(http_exception=403)
def audit_work_dealt():
    """
    Work orders has been handled.
    :return:
    """
    works = Work.query.filter(Work.audit_name == current_user.name, Work.status != 1)

    return render_template('audit/work_dealt.html', works=works)


@audit.route('/audit/work/detail/<int:id>')
@login_required
@audit_permission.require(http_exception=403)
def audit_work_detail(id):
    """
    Show more information about the work order and operations
    :param id:
    :return:
    """
    work = Work.query.get(id)
    backtimer = 0

    if work.timer is not None:
        backtimer = 1

    if work.status == 0 or work.status == 4:
        list_content = json.loads(work.execute_result)
    else:
        list_content = json.loads(work.auto_review)

    for content in list_content:
        content[4] = content[4].split('\n')
        content[5] = content[5].split('\r\n')

    return render_template('audit/work_detail.html', work=work, list_content=list_content, backtimer=backtimer)


@audit.route('/audit/work/cancel/<int:id>')
@login_required
@audit_permission.require(http_exception=403)
def audit_work_cancel(id):
    """
    Cancel the work order by auditor.
    :param id:
    :return:
    """
    work = Work.query.get(id)
    work.status = 6
    work.finish_time = datetime.now()
    db.session.add(work)
    db.session.commit()

    if current_app.config['MAIL_ON_OFF'] == 'ON':
        dev = User.query.filter(User.name == work.dev_name).first()
        mail_content = "<p>Work Sheet：" + work.name + " is cancelled by auditor. Please contact with your auditor.</p>"
        send_mail.delay('【inception_mysql】Work Sheet Cancelled', mail_content, dev.email)

    return redirect(url_for('.audit_work_dealt'))


@audit.route('/audit/work/reject/<int:id>')
@login_required
@audit_permission.require(http_exception=403)
def audit_work_reject(id):
    """
    Reject the work order by auditor.
    :param id:
    :return:
    """
    work = Work.query.get(id)
    work.status = 7
    work.finish_time = datetime.now()
    db.session.add(work)
    db.session.commit()

    if current_app.config['MAIL_ON_OFF'] == 'ON':
        dev = User.query.filter(User.name == work.dev_name).first()
        mail_content = "<p>Work Sheet：" + work.name + " is rejected by auditor. Please modify it.</p>"
        send_mail.delay('【inception_mysql】Work Sheet Rejected', mail_content, dev.email)

    return redirect(url_for('.audit_work_dealt'))


@audit.route('/audit/work/execute', methods=['POST'])
@audit_permission.require()
def audit_work_execute():
    data = request.form
    id = int(data['workflowid'])
    work = Work.query.filter(Work.id == id).first()

    if work.timer is None:
        work.task_id = str(id)
        work.status = 3
        work.man_review_time = datetime.now()

        # 执行之前重新split并check一遍，更新SHA1缓存；因为如果在执行中，其他进程去做这一步操作的话，会导致inception core dump挂掉
        split_review_result = sql_auto_review(work.sql_content, work.db_name, is_split='yes')
        work.auto_review = json.dumps(split_review_result)

        db.session.add(work)
        db.session.commit()

        async_result = execute_task.apply_async(args=[id], task_id=str(id))

        if current_app.config['MAIL_ON_OFF'] == 'ON':
            dev = User.query.filter(User.name == work.dev_name).first()
            mail_content = "<p>Work Sheet：" + work.name + " is executing. </p>" + "<p>Please view it</p>"
            send_mail.delay('【inception_mysql】Work Sheet Inform', mail_content, dev.email)

    return jsonify({}), 202, {'Location': url_for('.audit_work_detail', id=id)}


@audit.route('/audit/timer/work/<int:id>', methods=['GET', 'POST'])
@audit_permission.require(http_exception=403)
def audit_work_timer(id):
    """
    Set timer for work order.
    :param id:
    :return:
    """
    work = Work.query.get(id)
    if request.method == "POST":
        data = request.form
        timer = datetime.strptime(data["dt"], "%Y-%m-%d %H:%M")
        now = datetime.now()

        # Fix the celery 4.0.1 timezone bug.
        # See detail here https://github.com/celery/celery/pull/4173/
        eta = timer - timedelta(hours=8)

        if timer > now:
            sig = execute_task.signature((id,), eta=eta)
            if work.timer is None:
                async_result = sig.apply_async()
                work.task_id = async_result.id
                work.timer = timer

                db.session.add(work)
                db.session.commit()
            else:
                celery.control.revoke(work.task_id, terminate=True)
                async_result = sig.apply_async()
                work.task_id = async_result.id
                work.timer = timer

                db.session.add(work)
                db.session.commit()
        else:
            flash('Timer must later then now')

    return render_template('audit/work_timer.html', work=work)


@audit.route('/audit/timer/cancel/<int:id>')
@audit_permission.require(http_exception=403)
def audit_work_timer_cancel(id):
    """
    Cancel timer set.
    :param id:
    :return:
    """
    work = Work.query.get(id)
    celery.control.revoke(work.task_id, terminate=True)
    work.task_id = None
    work.timer = None

    db.session.add(work)
    db.session.commit()

    return redirect(url_for('.audit_work_timer', id=id))


@audit.route('/audit/timer/view')
@audit_permission.require(http_exception=403)
def audit_work_timer_view():
    """
    Show work orders which have timer.
    :return:
    """
    works = Work.query.filter(Work.timer != None).all()

    return render_template('audit/work_timer_view.html', works=works)


@audit.route('/audit/timer/detail/<int:id>')
@audit_permission.require(http_exception=403)
def audit_work_timer_detail(id):
    work = Work.query.get(id)

    return render_template('audit/work_timer_detail.html', work=work)


@audit.route('/timer_celery_status', methods=['POST'])
@audit_permission.require(http_exception=403)
def timer_celery_status():
    """
    Get status from celery.
    :return:
    """
    work_flow_tid = request.form['workflowtid']

    if work_flow_tid == '' or work_flow_tid is None:

app/templates/audit/resource_pending.html
{% extends 'main/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active"> Resources Pending</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title"> Resources Pending</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-hover" style="width: 100%">
                            <thead>
                            <tr>
                                <th>DB</th>
                                <th>Dev</th>
                                <th>CreateTime</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for resource in resources %}
                                <tr>
                                    <td>{{ resource.db_name }}</td>
                                    <td>{{ resource.dev_name }}</td>
                                    <td>{{ resource.create_time }}</td>
                                    <td>
                                        {% if resource.status == 0 %}
                                            Success
                                        {% elif resource.status == 1 %}
                                            Pending
                                        {% elif resource.status == 2 %}
                                            Dev Cancelled
                                        {% elif resource.status == 3 %}
                                            Audit Stopped
                                        {% endif %}
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-block btn-info btn-sm btn-flat"
                                                onclick="location.href='{{ url_for('audit.audit_resource_alloc', id=resource.id) }}'">
                                            Agree
                                        </button>

                                        <button type="button" class="btn btn-block btn-sm btn-danger btn-flat"
                                                onclick="location.href='{{ url_for('audit.audit_resource_cancel', id=resource.id) }}'">
                                            Cancel
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->

{% endblock %}

{% block js %}
    <!-- DataTables -->
    <script src="{{ url_for('static',filename='vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static',filename='vendor/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
{% endblock %}

{% block custom %}
    <script>
        $(function () {
            $('#example1').DataTable({
                scrollX: true
            });
        })
    </script>
{% endblock %}

app/templates/audit/work_dealt.html
{% extends 'main/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active"> Work Dealt</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Work Dealt Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-hover" style="width: 100%">
                            <thead>
                            <tr>
                                <th>WorkName</th>
                                <th>DB</th>
                                <th>Dev</th>
                                <th>Backup</th>
                                <th>CreateTime</th>
                                <th>FinishTime</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for work in works %}
                                <tr>
                                    <td>{{ work.name }}</td>
                                    <td>{{ work.db_name }}</td>
                                    <td>{{ work.dev_name }}</td>
                                    <td>
                                        {% if work.backup == true %}
                                        True
                                        {% else %}
                                        False
                                         {% endif %}
                                    </td>
                                    <td>
                                        {{ work.create_time }}
                                    </td>
                                    <td>
                                        {% if work.finish_time %}
                                        {{ work.finish_time }}
                                        {% else %}
                                        Unfinished
                                         {% endif %}
                                    </td>
                                    <td>
                                        {% if work.status == 0 %}
                                            Success
                                        {% elif work.status == 1 %}
                                            Pending
                                        {% elif work.status == 2 %}
                                            Check Failed
                                        {% elif work.status == 3 %}
                                            Executing
                                        {% elif work.status == 4 %}
                                            Error
                                        {% elif work.status == 5 %}
                                            Dev Cancelled
                                        {% elif work.status == 6 %}
                                            Audit Cancelled
                                        {% elif work.status == 7 %}
                                            Audit Rejected
                                        {% elif work.status == 8 %}
                                            Timing
                                        {% endif %}
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-block btn-sm bg-blue btn-flat"
                                                onclick="location.href='{{ url_for('audit.audit_work_detail', id=work.id) }}'">
                                            View
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->

{% endblock %}

{% block js %}
    <!-- DataTables -->
    <script src="{{ url_for('static',filename='vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static',filename='vendor/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
{% endblock %}

{% block custom %}
    <script>
        $(function () {
            $('#example1').DataTable({
                scrollX: true
            });
        })
    </script>
{% endblock %}

app/templates/audit/work_pending.html
{% extends 'main/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active"> Work Pending</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Work Pending Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-hover" style="width: 100%">
                            <thead>
                            <tr>
                                <th>WorkName</th>
                                <th>DB</th>
                                <th>Dev</th>
                                <th>Backup</th>
                                <th>CreateTime</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for work in works %}
                                <tr>
                                    <td>{{ work.name }}</td>
                                    <td>{{ work.db_name }}</td>
                                    <td>{{ work.dev_name }}</td>
                                    <td>
                                        {% if work.backup == true %}
                                        True
                                        {% else %}
                                        False
                                         {% endif %}
                                    </td>
                                    <td>
                                        {{ work.create_time }}
                                    </td>
                                    <td>
                                        Pending
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-block btn-sm bg-blue btn-flat"
                                                onclick="location.href='{{ url_for('audit.audit_work_detail', id=work.id) }}'">
                                            View
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->

{% endblock %}

{% block js %}
    <!-- DataTables -->
    <script src="{{ url_for('static',filename='vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static',filename='vendor/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
{% endblock %}

{% block custom %}
    <script>
        $(function () {
            $('#example1').DataTable({
                scrollX: true
            });
        })
    </script>
{% endblock %}

app/templates/audit/work_timer.html
{% extends 'main/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
            <li><a href="{{ url_for('audit.audit_work_detail', id=work.id) }}"> Work Detail</a></li>
            <li class="active"> Timer Set</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header box-primary">
                        <h3 class="box-title">Work Timer Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        {% for message in get_flashed_messages() %}
                            <div class="alert alert-warning">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            {{ message }}
                             </div>
                        {% endfor %}
                        <form method="post" action="{{ url_for('audit.audit_work_timer', id=work.id) }}">
                            <div class="form-group">
                                <label>状态：</label>
                                {% if work.timer %}
                                定时执行时间为 {{ work.timer }}
                                {% else %}
                                未设置定时时间
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label>Date:</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                <input type="text" class="form-control pull-right" id="dt" name="dt" required>
                                </div>
                            </div>

                            <div class="form-group">
                                {% if work.timer %}
                                <button type="button" class="btn btn-danger btn-flat"
                                        onclick="location.href='{{ url_for('audit.audit_work_timer_cancel', id=work.id) }}'">
                                    Cancel Timer
                                </button>
                                {% endif %}

                                <button type="submit" class="btn btn-primary btn-flat">
                                    Set Timer
                                </button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->

{% endblock %}

{% block js %}
    <!-- bootstrap datetimepicker -->
    <script src="{{ url_for('static',filename='vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
{% endblock %}

{% block custom %}
    <script>
        $(function () {
            $('#dt').datetimepicker({
                autoclose: true,
                todayBtn: true,
                format: 'yyyy-mm-dd hh:ii'
            })
        })
    </script>
{% endblock %}

app/templates/audit/work_timer_detail.html
{% extends 'main/base.html' %}

{% block content %}
    <input type="hidden" id="workflowTask_id" name="workflowid" value="{{ work.task_id }}">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
            <li><a href="{{ url_for('audit.audit_work_timer_view') }}"> Work Timer</a></li>
            <li class="active"> Detail</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Work Timer Detail</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-hover" style="width: 100%">
                            <thead>
                            <tr>
                                <th>DB</th>
                                <th>Dev</th>
                                <th>Backup</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ work.db_name }}</td>
                                    <td>{{ work.dev_name }}</td>
                                    <td>
                                        {% if work.backup == true %}
                                        True
                                        {% else %}
                                        False
                                        {% endif %}
                                    </td>
                                    <td>
                                        <B id="workflowCelery_status"></B>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-block btn-sm bg-navy btn-flat timer_set"
                                                onclick="location.href='{{ url_for('audit.audit_work_timer', id=work.id) }}'">
                                            Timer Set
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->

{% endblock %}

{% block js %}
    <!-- DataTables -->
    <script src="{{ url_for('static',filename='vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static',filename='vendor/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
{% endblock %}

{% block custom %}
    <script>
        $(function () {
            $('#example1').DataTable({
                scrollX: true
            });
        })
    </script>
{% endblock %}

{% block ajax %}

<script>
var workflowtaskid = $("#workflowTask_id").val();

var key;
$(document).ready(function(){
    var status = $("#workflowCelery_status").text();
    if (status === 'Executing' || status === ''){
        getWorkCeleryStatus(workflowtaskid);
        key = setInterval(function(){
            getWorkCeleryStatus(workflowtaskid);
        }, 1000)
    }
});

function getWorkCeleryStatus(wtid){
    $.ajax({
        type: "post",
        url: "{{ url_for('audit.timer_celery_status') }}",
        dataType: "json",
        data: {
            workflowtid: wtid
        },
        success: function (data) {
            wftStatus = data.status;
            content = data.msg;
            // console.log(typeof(wftStatus));
            console.log('wftStatus ' + wftStatus);
            console.log(content);
            document.getElementById("workflowCelery_status").innerHTML = content;
            if (content === 'Success') {
                document.getElementById("workflowCelery_status").style = "color: green";
            } else {
                document.getElementById("workflowCelery_status").style = "color: red";
            }
            if (content !== '' && content !== 'Wait') {
                $("button.timer_set").attr('disabled', 'True');
            }
            if (wftStatus === 4 || wftStatus === 0 || wftStatus === -1) {
                clearInterval(key);
    }
        }
    });
}
</script>
{% endblock %}