app/dev/__init__.py
from flask import Blueprint

dev = Blueprint('dev', __name__)

from . import views

app/dev/views.py
from datetime import datetime, date, timedelta
import re
import json

import sqlparse
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_login import login_required, current_user

from .. import db
from .. import dev_permission
from ..models import Dbapply, User, Dbconfig, Work
from .form import DbApplyForm, WorkForm, UpdateWorkForm
from ..inception import sql_auto_review
from ..tasks import send_mail
from . import dev


@dev.route('/dev/resource')
@login_required
@dev_permission.require(http_exception=403)
def dev_resource():
    """
    Show user's db instances.
    :return:
    """
    user = User.query.filter(User.name == current_user.name).first()
    resources = user.dbs

    return render_template('dev/resource.html', resources=resources, user=user)


@dev.route('/dev/resource/status')
@login_required
@dev_permission.require(http_exception=403)
def dev_resource_status():
    """
    Show user's application status
    :return:
    """
    resources = Dbapply.query.filter(Dbapply.dev_name == current_user.name)

    return render_template('dev/resource_status.html', resources=resources)


@dev.route('/dev/resource/cancel/<int:id>')
@login_required
@dev_permission.require(http_exception=403)
def dev_resource_cancel(id):
    """
    Dev users cancelled the application
    :param id:
    :return:
    """
    resource = Dbapply.query.get(id)
    resource.status = 2
    resource.finish_time = datetime.now()

    db.session.add(resource)
    db.session.commit()

    if current_app.config['MAIL_ON_OFF'] == 'ON':
        auditor = User.query.filter(User.name == resource.audit_name).first()
        mail_content = "<p>Proposer：" + resource.dev_name + "</p>" + "<p>Db instance's name：" + resource.db_name + \
                       "</p>" + "<p>Dev has cancelled the application.</p>"
        send_mail.delay('【inception_mysql】Db instance application cancelled', mail_content, auditor.email)

    return redirect(url_for('.dev_resource_status'))


@dev.route('/dev/resource/request', methods=['GET', 'POST'])
@login_required
@dev_permission.require(http_exception=403)
def dev_resource_request():
    """
    Apply for db instances.
    :return:
    """
    audits = User.query.filter(User.role == 'audit')
    user = User.query.filter(User.name == current_user.name).first()
    user_dbs = current_user.dbs
    all_dbs = Dbconfig.query.all()

    for user_db in user_dbs:
        if user_db in all_dbs:
            all_dbs.remove(user_db)

    form = DbApplyForm()
    if form.validate_on_submit():
        resource = Dbapply()
        resource.dev_name = current_user.name
        resource.db_name = form.db.data
        resource.audit_name = form.audit.data
        resource.status = 1
        resource.create_time = datetime.now()

        db.session.add(resource)
        db.session.commit()

        if current_app.config['MAIL_ON_OFF'] == 'ON':
            auditor = User.query.filter(User.name == resource.audit_name).first()
            mail_content = "<p>Proposer：" + resource.dev_name + "</p>" + "<p>Db instance's name：" + resource.db_name + \
                           "</p>" + "<p>New db instance request</p>"
            send_mail.delay('【inception_mysql】New db instance request', mail_content, auditor.email)

        return redirect(url_for('.dev_resource_status'))

    return render_template(
        'dev/resource_request.html',
        form=form,
        user=user,
        audits=audits,
        user_dbs=user_dbs,
        all_dbs=all_dbs
    )


@dev.route('/dev/work')
@login_required
@dev_permission.require(http_exception=403)
def dev_work():
    works = Work.query.filter(Work.dev_name == current_user.name)

    return render_template('dev/work.html', works=works)


@dev.route('/dev/work/create', methods=['GET', 'POST'])
@login_required
@dev_permission.require(http_exception=403)
def dev_work_create():
    """
    Create work order.
    :return:
    """
    db_ins = current_user.dbs
    audits = User.query.filter(User.role == 'audit')
    form = WorkForm()

    if form.validate_on_submit():
        sql_content = form.sql_content.data
        db_ins = form.db_ins.data
        shard = form.shard.data

        if form.backup.data:
            is_backup = True
        else:
            is_backup = False

        sql_content = sql_content.rstrip().replace("\n", " ")

        # Only Create and Alter can be used with table shard
        shard_create = re.search('\s*create\s+', sql_content, flags=re.IGNORECASE)
        shard_alter = re.search('\s*alter\s+', sql_content, flags=re.IGNORECASE)
        shard_judge = shard_create or shard_alter

        if shard != '0' and not shard_judge:
            flash('Only Create and Alter sql can be used when using table shard!')

            return redirect(url_for('.dev_work_create'))

        # split joint sql with shard numbers
        if shard != '0' and shard_judge:
            split_sql = sqlparse.split(sql_content)
            format_table = re.sub(" +", " ", split_sql[1])
            sql_content = ''

            for count in range(int(shard)):
                format_table_list = format_table.split(' ')
                shard_name = '`' + str(format_table_list[2].strip('`')) + '_' + str(count) + '`'
                format_table_list[2] = shard_name
                sql_content += ' '.join(format_table_list)
            sql_content = split_sql[0] + sql_content

        if sql_content[-1] == ';':
            work = Work()
            work.name = form.name.data
            work.db_name = form.db_ins.data
            work.shard = form.shard.data
            work.backup = is_backup
            work.dev_name = current_user.name
            work.audit_name = form.audit.data
            work.sql_content = sql_content

            result = sql_auto_review(sql_content, db_ins)

            if result or len(result) != 0:
                json_result = json.dumps(result)
                work.status = 1

                for row in result:
                    if row[2] == 2:
                        work.status = 2
                        break
                    elif re.match(r"\w*comments\w*", row[4]):
                        work.status = 2
                        break

                work.auto_review = json_result
                work.create_time = datetime.now()

                db.session.add(work)
                db.session.commit()

                if current_app.config['MAIL_ON_OFF'] == 'ON':
                    auditor = User.query.filter(User.name == work.audit_name).first()
                    mail_content = "<p>Proposer：" + work.dev_name + "</p>" + "<p>Sql Content：" + work.sql_content + \
                                   "</p>" + "<p>A new work sheet.</p>"
                    send_mail.delay('【inception_mysql】New work sheet', mail_content, auditor.email)

                return redirect(url_for('.dev_work'))
            else:
                flash('The return of Inception is null. May be something wrong with the SQL sentence ')

                return redirect(url_for('.dev_work_create'))
        else:
            flash('SQL sentences does not ends with ; Please Check!')

            return redirect(url_for('.dev_work_create'))

    return render_template('dev/work_create.html', form=form, db_ins=db_ins, audits=audits)


@dev.route('/dev/work/check', methods=['POST'])
@dev_permission.require(http_exception=403)
def dev_work_check():
    """
    SQL check button triggers this func.
    :return:
    """
    data = request.form
    sql_content = data['sql_content']
    db_in_name = data['db_in']
    shard = data['shard']
    final_result = {'status': 0, 'msg': 'ok', 'data': []}

    if not sql_content or not db_in_name:
        final_result['status'] = 1
        final_result['msg'] = 'DB or SQL is null !'

        return json.dumps(final_result)

    sql_content = sql_content.rstrip().replace("\n", " ")

    if sql_content[-1] != ';':
        final_result['status'] = 2
        final_result['msg'] = 'SQL not end with ; Please check !'

        return json.dumps(final_result)

    # Only Create and Alter can be used with table shard
    shard_create = re.search('\s*create\s+', sql_content, flags=re.IGNORECASE)
    shard_alter = re.search('\s*alter\s+', sql_content, flags=re.IGNORECASE)
    shard_judge = shard_create or shard_alter

    if shard != '0' and not shard_judge:
        final_result['status'] = 4
        final_result['msg'] = 'Only Create and Alter sql can be used when using table shard !'

        return json.dumps(final_result)

    # split joint sql with shard numbers
    if shard != '0' and shard_judge:
        split_sql = sqlparse.split(sql_content)
        format_table = re.sub(" +", " ", split_sql[1])
        sql_content = ''

        for count in range(int(shard)):
            format_table_list = format_table.split(' ')
            shard_name = '`' + str(format_table_list[2].strip('`')) + '_' + str(count) + '`'
            format_table_list[2] = shard_name
            sql_content += ' '.join(format_table_list)

        sql_content = split_sql[0] + sql_content

    # Submit the final SQL to Inception
    result = sql_auto_review(sql_content, db_in_name)

    if result is None or len(result) == 0:
        final_result['status'] = 3
        final_result['msg'] = 'The return of Inception is null. May be something wrong with the SQL'

        return json.dumps(final_result)

    final_result['data'] = result

    return json.dumps(final_result)


@dev.route('/dev/work/modify/<int:id>', methods=['GET', 'POST'])
@login_required
@dev_permission.require(http_exception=403)
def dev_work_modify(id):
    """
    Modify dev's work order.
    :param id:
    :return:
    """
    work = Work.query.get(id)
    db_ins = current_user.dbs
    audits = User.query.filter(User.role == 'audit')
    form = UpdateWorkForm()

    if form.validate_on_submit():
        shard = form.shard.data
        db_name = form.db_ins.data

        if form.backup.data:

app/templates/dev/dev_work_create.html
{% extends 'main/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
            <li><a href="{{ url_for('dev.dev_work') }}"> Workers</a></li>
            <li class="active">Add Worker</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Quick Add</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="post" action="{{ url_for('dev.dev_work_create') }}">
                        {{ form.hidden_tag() }}
                        <div class="box-body">
                            <div class="form-group">
                                <label for="WorkName">WorkName</label>
                                <input type="text" class="form-control" name="{{ form.name.name }}" required="required"
                                       placeholder="Enter WorkName">
                            </div>
                            <div class="form-group">
                                <label>DB</label>
                                <select id="{{ form.db_ins.name }}" class="form-control select2"
                                        name="{{ form.db_ins.name }}" required="required"
                                        style="width: 100%;">
                                    {% for db_in in db_ins %}
                                        <option value="{{ db_in.name }}">{{ db_in.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Shard</label>
                                <select id="{{ form.shard.name }}" class="form-control select2"
                                        name="{{ form.shard.name }}" required="required"
                                        style="width: 100%;">
                                    <option value="0">No Shard</option>
                                    <option value="64">64</option>
                                    <option value="256">256</option>
                                    <option value="512">512</option>
                                    <option value="1024">1024</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Backup</label>
                                <input type="radio" name="{{ form.backup.name }}" class="flat-red" checked>
                            </div>
                            <div class="form-group">
                                <label>Audit</label>
                                <select class="form-control select2" name="{{ form.audit.name }}" required="required"
                                        style="width: 100%;">
                                    {% for audit in audits %}
                                        <option value="{{ audit.name }}">{{ audit.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label>SQL Content</label>
                                <textarea id="{{ form.sql_content.name }}" class="form-control"
                                          name="{{ form.sql_content.name }}" rows="3" required="required"
                                          placeholder="Enter SQL Content"></textarea>
                                <button type="button" class="btn btn-primary" onclick="sql_check()">SQL Check</button>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="reset" class="btn btn-primary">Reset</button>
                            &nbsp;&nbsp;
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">SQL Check Result</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body" id="sql_check_result">

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->

{% endblock %}

{% block js %}
    <!-- Select2 -->
    <script src="{{ url_for('static',filename='vendor/select2/js/select2.full.min.js') }}"></script>
    <!-- iCheck 1.0.1 -->
    <script src="{{ url_for('static',filename='plugins/iCheck/icheck.min.js') }}"></script>
    <!-- SweetAlert2 -->
    <script src="{{ url_for('static',filename='vendor/sweetalert2/sweetalert2.min.js') }}"></script>
{% endblock %}

{% block custom %}
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2();

            //iCheck for checkbox and radio inputs
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue'
            });
            //Red color scheme for iCheck
            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass: 'iradio_minimal-red'
            });
            //Flat red color scheme for iCheck
            $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            });
        })
    </script>
{% endblock %}

{% block ajax %}
    <script>
        function sql_check() {
            var result = true;
            var sqlContent = $("#{{ fom.sql_content.name }}").val();
            var db_in = $("#{{ fom.db_ins.name }}").val();
            var shard = $("#{{ fom.shard.name }}").val();

            if (sqlContent === null || sqlContent.trim() === "") {
                swal('Oops...', 'SQL Content cat not be null', 'error');
                return result = false;
            } else if (db_in.length === 0) {
                swal('Oops...', 'Must choose a db instance', 'error')
                return result = false;
            }

            if (result === true) {
                $.ajax({
                    type: "post",
                    url: "{{ url_for('dev.dev_work_check') }}",
                    dataType: "json",
                    data: {
                        'sqlContent': sqlContent,
                        'db_in': db_in,
                        'shard': shard
                    },
                    success: function (data) {
                        if (data.status === 0) {
                            var result = data.data;
                            var finalHtml = "<div id='result'><table class='table'><thead><tr><th>sql语句</th><th>自动审核结果</th></tr></thead><tbody>";
                            for (var i = 0; i < result.length; i++) {
                                if (result[i][4] != "None") {
                                    finalresult = result[i][4].replace(/\n/g, "<br>")
                                    finalsql = result[i][5].replace(/\r\n/g, "<br>nbsp;nbsp;nbsp;nbsp;")
                                    finalsql = finalsql.replace(/,/g, ",<br>")
                                    finalHtml += "<tr><td><font color='#FF0000'>" + finalsql + "</font></td><td><font color='#FF0000'>" + finalresult + "</font></td></tr>"
                                } else {
                                    finalHtml += "<tr><td><font color='#00A600'>" + result[i][5] + "</font></td><td><font color='#00A600'>" + result[i][4] + "</font></td></tr>"
                                }
                            }
                            finalHtml += "</tbody></table></div>";
                            $('#result').remove();
                            $('#sql_check_result').append(finalHtml);
                        } else {
                            swal(data.msg, 'error');
                        }
                    }
                })
            }

        }
    </script>
{% endblock %}

app/templates/dev/resource.html
{% extends 'main/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Resources</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">{{ user.name }}'s DB resource</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">
                        <table class="table table-bordered">
                            {% if not resources %}
                                <tr>
                                    <td>No DB Resources Available</td>
                                </tr>
                            {% endif %}
                            {% for resource in resources %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>{{ resource.name }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->

{% endblock %}

{% block js %}
    <!-- Select2 -->
    <script src="{{ url_for('static',filename='vendor/select2/js/select2.full.min.js') }}"></script>
{% endblock %}

app/templates/dev/work_create.html
{% extends 'main/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Inception
            <small>MySQL</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.dashboard') }}"><i class="fa fa-home"></i> Home</a></li>
            <li><a href="{{ url_for('dev.dev_work') }}"> Workers</a></li>
            <li class="active">Add Worker</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Quick Add</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    {% for message in get_flashed_messages() %}
                    <div class="alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    <form role="form" method="post" action="{{ url_for('dev.dev_work_create') }}">
                        {{ form.hidden_tag() }}
                        <div class="box-body">
                            <div class="form-group">
                                <label for="WorkName">WorkName</label>
                                <input type="text" class="form-control" name="{{ form.name.name }}" required="required"
                                       placeholder="Enter WorkName">
                            </div>
                            <div class="form-group">
                                <label>DB</label>
                                <select id="{{ form.db_ins.name }}" class="form-control select2"
                                        name="{{ form.db_ins.name }}" required="required"
                                        style="width: 100%;">
                                    {% for db_in in db_ins %}
                                        <option value="{{ db_in.name }}">{{ db_in.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Shard</label>
                                <select id="{{ form.shard.name }}" class="form-control select2"
                                        name="{{ form.shard.name }}" required="required"
                                        style="width: 100%;">
                                    <option value="0">No Shard</option>
                                    <option value="64">64</option>
                                    <option value="256">256</option>
                                    <option value="512">512</option>
                                    <option value="1024">1024</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Backup</label>
                                <br>
                                <input type="checkbox" name="{{ form.backup.name }}" class="flat-red" value="True" checked>
                            </div>
                            <div class="form-group">
                                <label>Audit</label>
                                <select class="form-control select2" name="{{ form.audit.name }}" required="required"
                                        style="width: 100%;">
                                    {% for audit in audits %}
                                        <option value="{{ audit.name }}">{{ audit.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label>SQL Content</label>
                                <textarea id="{{ form.sql_content.name }}" class="form-control"
                                          name="{{ form.sql_content.name }}" rows="15" required="required"
                                          placeholder="Enter SQL Content"></textarea>
                                <br>
                                <button type="button" class="btn btn-primary" onclick="sql_check()">SQL Check</button>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="reset" class="btn btn-primary">Reset</button>
                            &nbsp;&nbsp;
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">SQL Check Result</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body" id="sql_check_result">

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>
    <!-- /.content -->

{% endblock %}

{% block js %}
    <!-- Select2 -->
    <script src="{{ url_for('static',filename='vendor/select2/js/select2.full.min.js') }}"></script>
    <!-- iCheck 1.0.1 -->
    <script src="{{ url_for('static',filename='vendor/iCheck/icheck.min.js') }}"></script>
    <!-- SweetAlert2 -->
    <script src="{{ url_for('static',filename='vendor/sweetalert2/sweetalert2.min.js') }}"></script>
{% endblock %}

{% block custom %}
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2();

            //iCheck for checkbox and radio inputs
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue'
            });
            //Red color scheme for iCheck
            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass: 'iradio_minimal-red'
            });
            //Flat red color scheme for iCheck
            $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            });
        })
    </script>
{% endblock %}

{% block ajax %}
    <script>
        function sql_check() {
            var result = true;
            var sql_content = $("#{{ form.sql_content.name }}").val();
            var db_in = $("#{{ form.db_ins.name }}").val();
            var shard = $("#{{ form.shard.name }}").val();

            if (sql_content === null || sql_content.trim() === "") {
                swal('Oops...', 'SQL Content cat not be null', 'error');
                return result = false;
            } else if (db_in.length === 0) {
                swal('Oops...', 'Must choose a db instance', 'error');
                return result = false;
            }

            if (result === true) {
                $.ajax({
                    type: "post",
                    url: "{{ url_for('dev.dev_work_check') }}",
                    dataType: "json",
                    data: {
                        'sql_content': sql_content,
                        'db_in': db_in,
                        'shard': shard
                    },
                    success: function (data) {
                        if (data.status === 0) {
                            var result = data.data;
                            var finalHtml = "<div id='result'><table class='table'><thead><tr><th>sql</th><th>Check result</th></tr></thead><tbody>";
                            for (var i = 0; i < result.length; i++) {
                                if (result[i][4] !== "None") {
                                    finalresult = result[i][4].replace(/\n/g, "<br>");
                                    finalsql = result[i][5].replace(/\r\n/g, "<br>nbsp;nbsp;nbsp;nbsp;");
                                    finalsql = finalsql.replace(/,/g, ",<br>");
                                    finalHtml += "<tr><td><font color='#FF0000'>" + finalsql + "</font></td><td><font color='#FF0000'>" + finalresult + "</font></td></tr>"
                                } else {
                                    finalHtml += "<tr><td><font color='#00A600'>" + result[i][5] + "</font></td><td><font color='#00A600'>" + result[i][4] + "</font></td></tr>"
                                }
                            }
                            finalHtml += "</tbody></table></div>";
                            $('#result').remove();
                            $('#sql_check_result').append(finalHtml);
                        } else {
                            swal('oops...', data.msg, 'error');
                        }
                    }
                })
            }

        }
    </script>
{% endblock %}